title: Privacy Extensions
author:
  name: Daniel Davis
description: Browser extensions for protecting your privacy online.

# Build settings
remote_theme: chrisrhymes/bulma-clean-theme
#theme: minima
